### ISSUE TITLE
jvmarg = -XX:+AggressiveOpts & Error on Java VM

### ISSUE THREAD

**Issue by CourteousGeek** [The-File/SK-Fixed#1]
"jvmarg = -XX:+AggressiveOpts" comes back from getdown.txt even when toggled Read-only.

**Comment by The-File** [comment]
This is what the "getdown-pro.jar" and "code/getdown-pro-new.jar" jars are for. Most likely forgot to copy those 2.

**Comment by The-File** [comment]
Let me know if the instructions were followed again. In case there is an issue with a file being reverted back by accident.

**Comment by CourteousGeek** [comment]
Upon renaming JDK-19 to "java_vm" and renaming the original "java_vm" it just gives Could not create the Java Virtual Machine, "A fatal exception has occured." Reverting to the original java_vm it works fine.

**Comment by The-File** [comment]
Using the original java_vm just makes it use your original java, aka not java 9+. Are you using any mods like Knight Launcher or using your own extra.txt instead of the one provided?

**Comment by CourteousGeek** [comment]
Not using any extra.txt or Knight Launcher just stock, Windows 11

**Comment by The-File** [comment]
Oh, you must use the extra.txt provided. Then modify off it instead if you want to change things.

**Comment by CourteousGeek** [comment]
Oh, okay. I'll try that.

**Comment by The-File** [comment]
If it's in the Windows folder, it's necessary.

**Comment by CourteousGeek** [comment]
It's up and running now, thanks!

**Comment by The-File** [comment]
No problem.
